# Generated by Django 4.1.9 on 2024-02-16 06:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="UnTitled", max_length=200)),
                (
                    "description",
                    models.CharField(
                        default="Author not provied any description", max_length=200
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="Author not provied any description", max_length=2000
                    ),
                ),
                (
                    "blog_profile_img",
                    models.CharField(
                        default="https://www.equalityhumanrights.com/sites/default/files/styles/listing_image/public/default_images/blog-teaser-default-full_5.jpg?itok=YOsTg-7X",
                        max_length=2000,
                    ),
                ),
                ("categories", models.CharField(max_length=200)),
                ("updated_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp_key", models.CharField(max_length=6)),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Awards",
        ),
        migrations.DeleteModel(
            name="Events",
        ),
        migrations.DeleteModel(
            name="Latest_News",
        ),
        migrations.DeleteModel(
            name="Mission",
        ),
        migrations.DeleteModel(
            name="Partners",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="Testimonials",
        ),
        migrations.DeleteModel(
            name="Value",
        ),
        migrations.DeleteModel(
            name="Vision",
        ),
        migrations.AlterModelOptions(
            name="logo",
            options={"get_latest_by": ["image"]},
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="date",
        ),
        migrations.RemoveField(
            model_name="logo",
            name="last_updated_date",
        ),
        migrations.AddField(
            model_name="gallery",
            name="L_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=12,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logo",
            name="Reson",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="logo",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=212,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gallery",
            name="G_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="categories",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                default="images/user_image.png", upload_to="Gallery/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="L_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(default="images/user_image.png", upload_to="logo"),
        ),
    ]
