# Generated by Django 4.1.9 on 2024-02-16 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_saveblog_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="category",
        ),
    ]
