# Generated by Django 4.1.9 on 2024-01-28 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0035_delete_about_delete_angelinvestordb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=12,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="G_id",
            field=models.CharField(max_length=200),
        ),
    ]
